package com.hpe.pointnext.appex.appsdev2.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author kumaindr
 *
 */
@Entity
@Table(name = "USERS", catalog = "TEST")
public class User {

	// An autogenerated id (unique for each user in the db)
	@Id
	@Column(name = "USERS_ID", unique = true, nullable = false, length = 12)
	@SequenceGenerator(name = "TEST.USERS_SEQUENCE", allocationSize = 1, initialValue = 1000000, sequenceName = "TEST.USERS_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TEST.USERS_SEQUENCE")
	private long id;

	// The user's email
	@Column(name = "EMAIL", nullable = false, updatable = false, unique=true)
	private String email;

	// The user's name
	@Column(name = "NAME", nullable = false, updatable = false, unique=true)
	private String name;

	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(String email, String name) {
		this.email = email;
		this.name = name;
	}

	// Getter and setter methods

	public long getId() {
		return id;
	}

	public void setId(long value) {
		this.id = value;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		this.email = value;
	}

	public String getName() {
		return name;
	}

	public void setName(String value) {
		this.name = value;
	}

}
